version: '3.8'

services:
  equipos-app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: sistema-equipos:production
    container_name: sistema-equipos-prod
    ports:
      - "127.0.0.1:8501:8501"  # Solo bind a localhost para usar con proxy
    volumes:
      # Usar volumen nombrado para mejor rendimiento en producción
      - equipos_db:/app
      - app_logs:/app/logs
    environment:
      - BASE_URL=${BASE_URL}
      - DB_PATH=equipos.db
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=true  # Habilitado en producción
      - STREAMLIT_SERVER_MAX_UPLOAD_SIZE=50
      - STREAMLIT_LOGGER_LEVEL=WARNING
    networks:
      - equipos_network
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Proxy reverso con Nginx (opcional)
  nginx:
    image: nginx:alpine
    container_name: nginx-equipos
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - equipos-app
    networks:
      - equipos_network
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  equipos_network:
    driver: bridge

volumes:
  equipos_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data
  app_logs:
    driver: local
  nginx_logs:
    driver: local